### ISSUE TITLE
driver/axidma_chrdev.c:275:5: error: implicit declaration of function 'of_dma_configure'

### ISSUE THREAD

**Issue by w66673733** [bperez77/xilinx_axidma#37]
function of_dma_configure() can not find.  in Linaro 12.11.

**Comment by bperez77** [comment]
What version of Linux does Linaro 12.11 use? It has to be a Linux 4.x version in order to compatible with the driver.

**Comment by w66673733** [comment]
The linux version is 4.0.0 the problem will occur.  when I use 4.6.0 it seems work,.
However, after I insmod axidma.ko, /dev/axidma is not created.

**Comment by bperez77** [comment]
Interesting, yeah some vendors don't backport all the changes from 4.x versions, so you can occasionally run into issues like this.

What's the output of `dmesg` immediately after you try to `insmod` the driver. If the device is not created, it is likely because there was a failure in the driver. This could be to a wide variety of problems.
